### ISSUE TITLE
open() does not wait for text editor to close

### ISSUE THREAD

**Issue by CharlesAverill** [jpsca/texteditor#2]
While using the open() function to open an existing file on macOS, the file will be opened but its changes will not be returned by the function.

When not opening an existing file, the text editor application will open but no document appears. Once again the function does not return any changes.

**Comment by jpsca** [comment]
Thanks for the report (and for the patience). I just pushed a fix. The cause was that the hardcoded editor commands were missing a `--wait` argument.

If you were having this problem with what you set in your `$EDITOR` env variable, consider adding a `--wait` parameter (or the equivalent) like it is advised here: https://docs.github.com/en/github/using-git/associating-text-editors-with-git
